/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppleMenu: typeof import('./components/menus/AppleMenu.vue')['default']
    Bear: typeof import('./components/apps/Bear.vue')['default']
    Boot: typeof import('./pages/Boot.vue')['default']
    Desktop: typeof import('./pages/Desktop.vue')['default']
    FaceTime: typeof import('./components/apps/FaceTime.vue')['default']
    HowDare: typeof import('./components/apps/Terminal/HowDare.vue')['default']
    Login: typeof import('./pages/Login.vue')['default']
    MenuItem: typeof import('./components/menus/base/MenuItem.vue')['default']
    MenuItemGroup: typeof import('./components/menus/base/MenuItemGroup.vue')['default']
    Terminal: typeof import('./components/apps/Terminal/Terminal.vue')['default']
    TopBar: typeof import('./components/menus/TopBar.vue')['default']
    WifiMenu: typeof import('./components/menus/WifiMenu.vue')['default']
  }
}
